import React, { useState } from 'react';
import { Download, MessageCircle, Link as LinkIcon, CheckCircle } from 'lucide-react';
import html2canvas from 'html2canvas';

const tagConfig = {
  Aggressor: { bg: "bg-aggressor-bg", text: "text-aggressor-text", border: "border-aggressor-border", glow: "tag-glow-green", icon: "⚡" },
  Anchor:    { bg: "bg-anchor-bg", text: "text-anchor-text", border: "border-anchor-border", glow: "tag-glow-blue", icon: "🛡" },
  Improving: { bg: "bg-improving-bg", text: "text-improving-text", border: "border-improving-border", glow: "tag-glow-yellow", icon: "📈" },
  Liability: { bg: "bg-liability-bg", text: "text-liability-text", border: "border-liability-border", glow: "tag-glow-red", icon: "⚠" }
};

export default function PlayerCard({ player, hideActions = false }) {
  const [copied, setCopied] = useState(false);
  const config = tagConfig[player.tag] || tagConfig.Anchor;
  const cardId = `player-card-${player.name.replace(/\s+/g, '-')}`;

  const handleShare = async () => {
    const element = document.getElementById(cardId);
    if (!element) return;
    try {
      const isDark = document.documentElement.classList.contains('dark');
      const canvas = await html2canvas(element, {
        backgroundColor: isDark ? '#0A0C10' : '#F8FAFC',
        scale: 2,
      });
      const link = document.createElement('a');
      link.download = `CoachLens-${player.name}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    } catch (err) {
      console.error('Failed to generate image', err);
    }
  };

  const handleWhatsAppShare = () => {
    const text = `🏏 *CoachLens Player Report* 🏏\n\n👤 *${player.name}* (${player.role})\n⚡ Rating: ${player.tag}${player.match_impact ? ` (${player.match_impact}/10 Impact)` : ''}\n${player.key_stat ? `📊 Key Stat: ${player.key_stat}\n` : ''}\n✅ *What Worked:*\n${player.what_worked}\n\n❌ *What Failed:*\n${player.what_failed}\n\n🎯 *Next Match Focus:*\n${player.next_match_instruction}\n\n💪 *Practice Drill:*\n${player.practice_drill}\n\n_Generated by CoachLens AI 🧠_`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
  };

  const handleCopyLink = () => {
    try {
      const jsonString = JSON.stringify(player);
      const encoded = btoa(unescape(encodeURIComponent(jsonString)));
      const url = `${window.location.origin}/card?data=${encoded}`;
      navigator.clipboard.writeText(url);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to generate link", err);
    }
  };

  const highlightNumbers = (text) => {
    if (!text) return text;
    return text.split(/(\d+(?:\.\d+)?%?)/g).map((part, i) => {
      if (/\d/.test(part)) {
        return <span key={i} className="text-accent font-semibold">{part}</span>;
      }
      return part;
    });
  };

  const sections = [
    { label: "What Worked", icon: "✓", text: player.what_worked, color: "text-aggressor-text" },
    { label: "What Failed", icon: "✗", text: player.what_failed, color: "text-liability-text" },
    { label: "Next Match", icon: "→", text: player.next_match_instruction, color: "text-accent" },
    { label: "Drill", icon: "◉", text: player.practice_drill, color: "text-anchor-text" },
  ];

  return (
    <div 
      id={cardId} 
      className={`relative glass-card rounded-xl border-l-[3px] ${config.border} p-5 flex flex-col group`}
    >
      {/* Header */}
      <div className="flex justify-between items-start mb-1">
        <div>
          <h3 className="font-display text-xl leading-tight">{player.name}</h3>
          <p className="text-xs text-textSecondary mt-1 font-mono">{player.role}</p>
          {(player.key_stat || player.match_impact) && (
            <div className="flex gap-3 mt-1.5 text-[10px] font-mono text-textTertiary uppercase tracking-wider">
              {player.key_stat && <span>📊 {player.key_stat}</span>}
              {player.match_impact && <span>⭐ {player.match_impact}/10</span>}
            </div>
          )}
        </div>
        <div className={`${config.bg} ${config.text} border ${config.border} px-2.5 py-1 rounded-lg text-[10px] uppercase font-bold tracking-wider animate-scale-pop flex items-center gap-1`}>
          <span>{config.icon}</span>
          {player.tag}
        </div>
      </div>
      
      {/* Divider */}
      <div className="divider-accent my-4" />

      {/* Sections */}
      <div className="space-y-4 flex-1">
        {sections.map((section, idx) => (
          <div key={idx}>
            <h4 className="text-[10px] uppercase tracking-[0.2em] mb-1.5 font-medium flex items-center gap-1.5">
              <span className={section.color}>{section.icon}</span>
              <span className="text-textSecondary">{section.label}</span>
            </h4>
            <p className="text-sm leading-relaxed text-textPrimary/90">{highlightNumbers(section.text)}</p>
          </div>
        ))}
      </div>

      {/* Share Actions */}
      {!hideActions && (
        <div className="flex flex-wrap items-center justify-end gap-3 mt-5 pt-3 border-t border-border" data-html2canvas-ignore="true">
          <button 
            onClick={handleCopyLink}
            className="text-xs text-textSecondary hover:text-textPrimary flex items-center gap-1 transition-colors px-2 py-1 rounded-lg hover:bg-surface2"
            title="Copy Public Web Link"
          >
            {copied ? <CheckCircle size={12} className="text-aggressor-text" /> : <LinkIcon size={12} />} 
            {copied ? <span className="text-aggressor-text">Copied!</span> : 'Link'}
          </button>
          <button 
            onClick={handleWhatsAppShare}
            className="text-xs text-textSecondary hover:text-aggressor-text flex items-center gap-1 transition-colors px-2 py-1 rounded-lg hover:bg-aggressor-bg"
            title="Share via WhatsApp"
          >
            <MessageCircle size={12} /> WhatsApp
          </button>
          <button 
            onClick={handleShare}
            className="text-xs text-textSecondary hover:text-accent flex items-center gap-1 transition-colors px-2 py-1 rounded-lg hover:bg-surface2"
            title="Download Card as Image"
          >
            <Download size={12} /> Download
          </button>
        </div>
      )}
    </div>
  );
}
