import React, { useState, useEffect, useMemo } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { ArrowLeft, Target, Shield, Zap, History, Send, MessageSquare } from 'lucide-react';
import { storageService } from '../services/storageService';
import { calculateIntentScore, getPressureIndex, calculateClutchFactors } from '../utils/coachingMetrics';

export default function PlayerProfile() {
  const { playerName } = useParams();
  const name = decodeURIComponent(playerName);
  const navigate = useNavigate();

  const [matches, setMatches] = useState([]);
  const [allMatches, setAllMatches] = useState([]);
  
  useEffect(() => {
    const loadData = async () => {
      const stored = await storageService.getMatches();
      setAllMatches(stored);

      const playerMatches = [];
      stored.forEach(match => {
        if (match.analysis && match.analysis.players) {
          const player = match.analysis.players.find(p => p.name === name);
          if (player) {
            playerMatches.push({
              matchId: match.id,
              date: match.date,
              teamName: match.teamName,
              opponent: match.opponent,
              result: match.result,
              ...player
            });
          }
        }
      });

      setMatches(playerMatches.sort((a, b) => new Date(b.date) - new Date(a.date)));
    };
    loadData();
  }, [name]);

  const clutchData = useMemo(() => {
    const data = calculateClutchFactors(allMatches);
    return data[name] || null;
  }, [allMatches, name]);

  const latestPlayer = matches[0];
  const intent = latestPlayer ? calculateIntentScore(latestPlayer) : null;
  const pressure = latestPlayer ? getPressureIndex(latestPlayer) : null;

  const handleWhatsAppShare = () => {
    if (!latestPlayer) return;
    
    // Aggregate the latest 2 drills or feedback
    const recentFeedback = matches.slice(0, 2).map(m => m.practice_drill).filter(Boolean);
    const feedbackText = recentFeedback.length > 0 
      ? `Coach Note: Focus on ${recentFeedback[0].toLowerCase()}`
      : `Coach Note: Review your latest match analysis.`;

    const text = `🏏 *CoachLens Player Report: ${name}*\n\n` +
      `Role: ${latestPlayer.role}\n` +
      `Current Form: ${latestPlayer.tag}\n` +
      `Intent Score: ${intent?.score || 'N/A'}/10\n\n` +
      `${feedbackText}\n\n` +
      `_Generated by CoachLens_`;
    
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
  };

  const getTagColor = (tag) => {
    if (tag === 'Aggressor') return 'text-aggressor-text bg-aggressor-bg border-aggressor-border';
    if (tag === 'Anchor') return 'text-anchor-text bg-anchor-bg border-anchor-border';
    if (tag === 'Liability') return 'text-liability-text bg-liability-bg border-liability-border';
    if (tag === 'Improving') return 'text-improving-text bg-improving-bg border-improving-border';
    return 'text-textSecondary bg-surface2 border-border';
  };

  return (
    <div className="p-6 md:p-10 max-w-5xl mx-auto space-y-8 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <button onClick={() => navigate(-1)} className="p-2 rounded-xl bg-surface2 hover:bg-surface3 border border-border text-textSecondary hover:text-textPrimary transition-all">
            <ArrowLeft size={18} />
          </button>
          <div>
            <h1 className="text-display-xl font-display text-textPrimary">{name}</h1>
            <p className="text-sm font-mono text-textSecondary">{latestPlayer?.role || 'Unknown Role'} • {matches.length} Matches Analyzed</p>
          </div>
        </div>
        <button onClick={handleWhatsAppShare} className="flex items-center justify-center gap-2 bg-aggressor-bg text-aggressor-text hover:bg-aggressor-bg/80 border border-aggressor-border px-5 py-3 rounded-xl text-sm font-mono font-bold tracking-wider uppercase transition-all btn-press">
          <MessageSquare size={16} /> Send Report
        </button>
      </div>

      {matches.length === 0 ? (
        <div className="glass-card p-12 text-center rounded-2xl border-dashed border-border">
          <p className="text-textSecondary font-mono text-sm">No analysis history found for {name}.</p>
        </div>
      ) : (
        <>
          {/* Key Metrics */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="glass-card p-5 rounded-2xl">
              <div className="text-[10px] text-textTertiary uppercase font-mono mb-2 flex items-center gap-1"><Target size={12}/> Current Form</div>
              <div className={`inline-block px-3 py-1 rounded-lg text-xs font-mono uppercase tracking-wider border ${getTagColor(latestPlayer?.tag)}`}>
                {latestPlayer?.tag || 'Unknown'}
              </div>
            </div>
            
            <div className="glass-card p-5 rounded-2xl">
              <div className="text-[10px] text-textTertiary uppercase font-mono mb-2 flex items-center gap-1"><Zap size={12}/> Intent Score</div>
              <div className="text-2xl font-display text-textPrimary">
                {intent?.score || '--'} <span className="text-sm text-textSecondary font-mono">/10</span>
              </div>
              <div className={`text-[10px] font-mono mt-1 ${intent?.color ? `text-${intent.color}-text` : 'text-textTertiary'}`}>
                {intent?.label || 'Calculating...'}
              </div>
            </div>

            <div className="glass-card p-5 rounded-2xl">
              <div className="text-[10px] text-textTertiary uppercase font-mono mb-2 flex items-center gap-1"><Shield size={12}/> Clutch Factor</div>
              <div className="text-2xl font-display text-textPrimary">
                {clutchData?.badge || 'Consistent'}
              </div>
              <div className="text-[10px] font-mono text-textTertiary mt-1">
                Win Avg: {clutchData?.winAvg || '--'} • Loss Avg: {clutchData?.lossAvg || '--'}
              </div>
            </div>

            <div className="glass-card p-5 rounded-2xl">
              <div className="text-[10px] text-textTertiary uppercase font-mono mb-2 flex items-center gap-1"><Zap size={12}/> Pressure Index</div>
              {pressure ? (
                <div className={`inline-flex items-center gap-2 px-3 py-1 mt-1 rounded-lg text-xs font-mono uppercase tracking-wider bg-${pressure.color}-bg text-${pressure.color}-text border border-${pressure.color}-border`}>
                  {pressure.icon} {pressure.label}
                </div>
              ) : (
                <div className="text-sm font-mono text-textTertiary mt-2">No pressure flags</div>
              )}
            </div>
          </div>

          {/* Historical Analysis Feed */}
          <div>
            <h2 className="text-lg font-display text-textPrimary flex items-center gap-2 mb-4">
              <History size={18} className="text-accent" /> Analysis History
            </h2>
            
            <div className="space-y-4">
              {matches.map(match => (
                <div key={match.matchId} className="glass-card rounded-2xl p-6 relative overflow-hidden group">
                  <div className={`absolute left-0 top-0 bottom-0 w-1 ${getTagColor(match.tag).split(' ')[1]}`} />
                  
                  <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-4 pb-4 border-b border-border/50">
                    <div>
                      <div className="flex items-center gap-2 mb-1">
                        <h3 className="font-display text-textPrimary text-lg">vs {match.opponent}</h3>
                        <span className={`text-[9px] uppercase tracking-wider font-mono px-2 py-0.5 rounded border ${match.result === 'Won' ? 'bg-aggressor-bg text-aggressor-text border-aggressor-border' : 'bg-liability-bg text-liability-text border-liability-border'}`}>
                          {match.result}
                        </span>
                      </div>
                      <div className="text-xs font-mono text-textSecondary">{new Date(match.date).toLocaleDateString()} • {match.teamName}</div>
                    </div>
                    <Link to={`/match/${match.matchId}`} className="text-xs font-mono text-accent hover:text-accentHover underline">
                      View Full Match
                    </Link>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div className="space-y-4">
                      <div>
                        <div className="text-[10px] text-aggressor-text uppercase font-mono tracking-widest mb-1.5 flex items-center gap-2">✓ What Worked</div>
                        <p className="text-sm text-textSecondary leading-relaxed">{match.what_worked || 'No data.'}</p>
                      </div>
                      <div>
                        <div className="text-[10px] text-liability-text uppercase font-mono tracking-widest mb-1.5 flex items-center gap-2">✗ What Failed</div>
                        <p className="text-sm text-textSecondary leading-relaxed">{match.what_failed || 'No data.'}</p>
                      </div>
                    </div>
                    
                    <div className="space-y-4">
                      <div className="bg-surface2 p-4 rounded-xl border border-border">
                        <div className="text-[10px] text-accent uppercase font-mono tracking-widest mb-2 flex items-center gap-2">→ Next Match Focus</div>
                        <p className="text-sm text-textPrimary leading-relaxed">{match.next_match_instruction || 'No instructions.'}</p>
                      </div>
                      <div className="bg-surface2 p-4 rounded-xl border border-border">
                        <div className="text-[10px] text-textSecondary uppercase font-mono tracking-widest mb-2 flex items-center gap-2">◉ Practice Drill</div>
                        <p className="text-sm text-textPrimary leading-relaxed">{match.practice_drill || 'No drill provided.'}</p>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </>
      )}
    </div>
  );
}
